# Arquivo: render.yaml
# Versão final CORRIGIDA para deploy com PostgreSQL

services:
  # Define apenas o Serviço Web (sua aplicação Flask)
  - type: web
    name: painel-backend   # Nome do seu serviço web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT main:app"
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5

      # Conecta-se ao banco de dados que JÁ EXISTE no Render.
      - key: DATABASE_URL
        fromDatabase:
          name: baccc  # O nome do seu banco de dados PostgreSQL
          # CORREÇÃO: A propriedade correta é 'connectionString'
          property: connectionString
